package zkz.bangong.layui;

import java.io.Serializable;
import java.util.Date;

public class crmTaskLayuiComment implements Serializable {
    @Override
    public String toString() {
        return "crmTaskLayuiComment{" +
                "cmmentId=" + cmmentId +
                ", userId=" + userId +
                ", userName='" + userName + '\'' +
                ", content='" + content + '\'' +
                ", createTime=" + createTime +
                ", mainId=" + mainId +
                ", pid=" + pid +
                ", pName='" + pName + '\'' +
                ", status=" + status +
                ", typeId=" + typeId +
                ", favour=" + favour +
                ", commentType=" + commentType +
                '}';
    }

    private Integer cmmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.user_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer userId;

    private String userName;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.content
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.create_time
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.main_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer mainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.pid
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer pid;

    private String pName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getpName() {
        return pName;
    }

    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.status
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.type_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.favour
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer favour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_comment.comment_type
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    private Integer commentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.cmment_id
     *
     * @return the value of crm_task_comment.cmment_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getCmmentId() {
        return cmmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.cmment_id
     *
     * @param cmmentId the value for crm_task_comment.cmment_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setCmmentId(Integer cmmentId) {
        this.cmmentId = cmmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.user_id
     *
     * @return the value of crm_task_comment.user_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.user_id
     *
     * @param userId the value for crm_task_comment.user_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.content
     *
     * @return the value of crm_task_comment.content
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.content
     *
     * @param content the value for crm_task_comment.content
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.create_time
     *
     * @return the value of crm_task_comment.create_time
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.create_time
     *
     * @param createTime the value for crm_task_comment.create_time
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.main_id
     *
     * @return the value of crm_task_comment.main_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.main_id
     *
     * @param mainId the value for crm_task_comment.main_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.pid
     *
     * @return the value of crm_task_comment.pid
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.pid
     *
     * @param pid the value for crm_task_comment.pid
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.status
     *
     * @return the value of crm_task_comment.status
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.status
     *
     * @param status the value for crm_task_comment.status
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.type_id
     *
     * @return the value of crm_task_comment.type_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.type_id
     *
     * @param typeId the value for crm_task_comment.type_id
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.favour
     *
     * @return the value of crm_task_comment.favour
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getFavour() {
        return favour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.favour
     *
     * @param favour the value for crm_task_comment.favour
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setFavour(Integer favour) {
        this.favour = favour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_comment.comment_type
     *
     * @return the value of crm_task_comment.comment_type
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_comment.comment_type
     *
     * @param commentType the value for crm_task_comment.comment_type
     *
     * @mbg.generated Tue Oct 22 16:55:02 CST 2019
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }
}
