package zkz.bangong.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class chaiLvExamine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.start_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.to_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String toCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.fare
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal fare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.live_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal liveMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.food_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal foodMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.other_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal otherMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.other_context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal otherContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_chailv_examine.total_moey
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private BigDecimal totalMoey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.examine_id
     *
     * @return the value of crm_chailv_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.examine_id
     *
     * @param examineId the value for crm_chailv_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.creater
     *
     * @return the value of crm_chailv_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.creater
     *
     * @param creater the value for crm_chailv_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.examine_type
     *
     * @return the value of crm_chailv_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineType() {
        return examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.examine_type
     *
     * @param examineType the value for crm_chailv_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineType(Integer examineType) {
        this.examineType = examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.context
     *
     * @return the value of crm_chailv_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.context
     *
     * @param context the value for crm_chailv_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.img_addr
     *
     * @return the value of crm_chailv_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.img_addr
     *
     * @param imgAddr the value for crm_chailv_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.batch_id
     *
     * @return the value of crm_chailv_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.batch_id
     *
     * @param batchId the value for crm_chailv_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.create_time
     *
     * @return the value of crm_chailv_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.create_time
     *
     * @param createTime the value for crm_chailv_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.update_time
     *
     * @return the value of crm_chailv_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.update_time
     *
     * @param updateTime the value for crm_chailv_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.examine_user_id
     *
     * @return the value of crm_chailv_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineUserId() {
        return examineUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.examine_user_id
     *
     * @param examineUserId the value for crm_chailv_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineUserId(Integer examineUserId) {
        this.examineUserId = examineUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.start_city
     *
     * @return the value of crm_chailv_examine.start_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.start_city
     *
     * @param startCity the value for crm_chailv_examine.start_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.to_city
     *
     * @return the value of crm_chailv_examine.to_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getToCity() {
        return toCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.to_city
     *
     * @param toCity the value for crm_chailv_examine.to_city
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setToCity(String toCity) {
        this.toCity = toCity == null ? null : toCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.start_time
     *
     * @return the value of crm_chailv_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.start_time
     *
     * @param startTime the value for crm_chailv_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.end_time
     *
     * @return the value of crm_chailv_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.end_time
     *
     * @param endTime the value for crm_chailv_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.fare
     *
     * @return the value of crm_chailv_examine.fare
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getFare() {
        return fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.fare
     *
     * @param fare the value for crm_chailv_examine.fare
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setFare(BigDecimal fare) {
        this.fare = fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.live_money
     *
     * @return the value of crm_chailv_examine.live_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getLiveMoney() {
        return liveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.live_money
     *
     * @param liveMoney the value for crm_chailv_examine.live_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setLiveMoney(BigDecimal liveMoney) {
        this.liveMoney = liveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.food_money
     *
     * @return the value of crm_chailv_examine.food_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getFoodMoney() {
        return foodMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.food_money
     *
     * @param foodMoney the value for crm_chailv_examine.food_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setFoodMoney(BigDecimal foodMoney) {
        this.foodMoney = foodMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.other_money
     *
     * @return the value of crm_chailv_examine.other_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getOtherMoney() {
        return otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.other_money
     *
     * @param otherMoney the value for crm_chailv_examine.other_money
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setOtherMoney(BigDecimal otherMoney) {
        this.otherMoney = otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.other_context
     *
     * @return the value of crm_chailv_examine.other_context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getOtherContext() {
        return otherContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.other_context
     *
     * @param otherContext the value for crm_chailv_examine.other_context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setOtherContext(BigDecimal otherContext) {
        this.otherContext = otherContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_chailv_examine.total_moey
     *
     * @return the value of crm_chailv_examine.total_moey
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public BigDecimal getTotalMoey() {
        return totalMoey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_chailv_examine.total_moey
     *
     * @param totalMoey the value for crm_chailv_examine.total_moey
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setTotalMoey(BigDecimal totalMoey) {
        this.totalMoey = totalMoey;
    }
}