package zkz.bangong.pojo;

import java.util.Date;

public class crmAnnoun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.announcement_id_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Integer announcementIdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.title
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.content
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.create_user_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.create_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.update_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.start_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.end_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_oa_announcement.dept_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.announcement_id_id
     *
     * @return the value of crm_oa_announcement.announcement_id_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Integer getAnnouncementIdId() {
        return announcementIdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.announcement_id_id
     *
     * @param announcementIdId the value for crm_oa_announcement.announcement_id_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setAnnouncementIdId(Integer announcementIdId) {
        this.announcementIdId = announcementIdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.title
     *
     * @return the value of crm_oa_announcement.title
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.title
     *
     * @param title the value for crm_oa_announcement.title
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.content
     *
     * @return the value of crm_oa_announcement.content
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.content
     *
     * @param content the value for crm_oa_announcement.content
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.create_user_id
     *
     * @return the value of crm_oa_announcement.create_user_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.create_user_id
     *
     * @param createUserId the value for crm_oa_announcement.create_user_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.create_time
     *
     * @return the value of crm_oa_announcement.create_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.create_time
     *
     * @param createTime the value for crm_oa_announcement.create_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.update_time
     *
     * @return the value of crm_oa_announcement.update_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.update_time
     *
     * @param updateTime the value for crm_oa_announcement.update_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.start_time
     *
     * @return the value of crm_oa_announcement.start_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.start_time
     *
     * @param startTime the value for crm_oa_announcement.start_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.end_time
     *
     * @return the value of crm_oa_announcement.end_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.end_time
     *
     * @param endTime the value for crm_oa_announcement.end_time
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_oa_announcement.dept_id
     *
     * @return the value of crm_oa_announcement.dept_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_oa_announcement.dept_id
     *
     * @param deptId the value for crm_oa_announcement.dept_id
     *
     * @mbg.generated Thu Oct 24 18:01:36 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}