package zkz.bangong.pojo;

import java.util.Date;

public class crmTaskLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.log_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.content
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task_log.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer workId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.log_id
     *
     * @return the value of crm_task_log.log_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.log_id
     *
     * @param logId the value for crm_task_log.log_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.user_id
     *
     * @return the value of crm_task_log.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.user_id
     *
     * @param userId the value for crm_task_log.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.content
     *
     * @return the value of crm_task_log.content
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.content
     *
     * @param content the value for crm_task_log.content
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.create_time
     *
     * @return the value of crm_task_log.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.create_time
     *
     * @param createTime the value for crm_task_log.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.status
     *
     * @return the value of crm_task_log.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.status
     *
     * @param status the value for crm_task_log.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.task_id
     *
     * @return the value of crm_task_log.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.task_id
     *
     * @param taskId the value for crm_task_log.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task_log.work_id
     *
     * @return the value of crm_task_log.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task_log.work_id
     *
     * @param workId the value for crm_task_log.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }
}