package zkz.bangong.pojo;

import java.util.Date;

public class crmTask {
    @Override
    public String toString() {
        return "crmTask{" +
                "taskId=" + taskId +
                ", taskName='" + taskName + '\'' +
                ", createUserId=" + createUserId +
                ", mainUserId=" + mainUserId +
                ", ownerUserId=" + ownerUserId +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", status=" + status +
                ", labelId='" + labelId + '\'' +
                ", pid=" + pid +
                ", startTime=" + startTime +
                ", stopTime=" + stopTime +
                ", priority=" + priority +
                ", workId=" + workId +
                ", isTop=" + isTop +
                ", isOpen=" + isOpen +
                ", archiveTime=" + archiveTime +
                ", ishidden=" + ishidden +
                ", hiddenTime=" + hiddenTime +
                ", batchId='" + batchId + '\'' +
                ", isArchive=" + isArchive +
                ", description='" + description + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.task_name
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.create_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.main_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer mainUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.owner_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.update_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.label_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.pid
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.start_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.stop_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.priority
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.is_top
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.is_open
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.archive_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date archiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.ishidden
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer ishidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.hidden_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date hiddenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.batch_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.is_archive
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer isArchive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_task.description
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.task_id
     *
     * @return the value of crm_task.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.task_id
     *
     * @param taskId the value for crm_task.task_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.task_name
     *
     * @return the value of crm_task.task_name
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.task_name
     *
     * @param taskName the value for crm_task.task_name
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.create_user_id
     *
     * @return the value of crm_task.create_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.create_user_id
     *
     * @param createUserId the value for crm_task.create_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.main_user_id
     *
     * @return the value of crm_task.main_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getMainUserId() {
        return mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.main_user_id
     *
     * @param mainUserId the value for crm_task.main_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setMainUserId(Integer mainUserId) {
        this.mainUserId = mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.owner_user_id
     *
     * @return the value of crm_task.owner_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.owner_user_id
     *
     * @param ownerUserId the value for crm_task.owner_user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setOwnerUserId(Integer ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.create_time
     *
     * @return the value of crm_task.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.create_time
     *
     * @param createTime the value for crm_task.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.update_time
     *
     * @return the value of crm_task.update_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.update_time
     *
     * @param updateTime the value for crm_task.update_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.status
     *
     * @return the value of crm_task.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.status
     *
     * @param status the value for crm_task.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.label_id
     *
     * @return the value of crm_task.label_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.label_id
     *
     * @param labelId the value for crm_task.label_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId == null ? null : labelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.pid
     *
     * @return the value of crm_task.pid
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.pid
     *
     * @param pid the value for crm_task.pid
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.start_time
     *
     * @return the value of crm_task.start_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.start_time
     *
     * @param startTime the value for crm_task.start_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.stop_time
     *
     * @return the value of crm_task.stop_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.stop_time
     *
     * @param stopTime the value for crm_task.stop_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.priority
     *
     * @return the value of crm_task.priority
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.priority
     *
     * @param priority the value for crm_task.priority
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.work_id
     *
     * @return the value of crm_task.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.work_id
     *
     * @param workId the value for crm_task.work_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.is_top
     *
     * @return the value of crm_task.is_top
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.is_top
     *
     * @param isTop the value for crm_task.is_top
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.is_open
     *
     * @return the value of crm_task.is_open
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.is_open
     *
     * @param isOpen the value for crm_task.is_open
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.archive_time
     *
     * @return the value of crm_task.archive_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getArchiveTime() {
        return archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.archive_time
     *
     * @param archiveTime the value for crm_task.archive_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setArchiveTime(Date archiveTime) {
        this.archiveTime = archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.ishidden
     *
     * @return the value of crm_task.ishidden
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getIshidden() {
        return ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.ishidden
     *
     * @param ishidden the value for crm_task.ishidden
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setIshidden(Integer ishidden) {
        this.ishidden = ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.hidden_time
     *
     * @return the value of crm_task.hidden_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getHiddenTime() {
        return hiddenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.hidden_time
     *
     * @param hiddenTime the value for crm_task.hidden_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setHiddenTime(Date hiddenTime) {
        this.hiddenTime = hiddenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.batch_id
     *
     * @return the value of crm_task.batch_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.batch_id
     *
     * @param batchId the value for crm_task.batch_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.is_archive
     *
     * @return the value of crm_task.is_archive
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getIsArchive() {
        return isArchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.is_archive
     *
     * @param isArchive the value for crm_task.is_archive
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setIsArchive(Integer isArchive) {
        this.isArchive = isArchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_task.description
     *
     * @return the value of crm_task.description
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_task.description
     *
     * @param description the value for crm_task.description
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}