package zkz.bangong.pojo;

import java.util.Date;

public class crmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.username
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.password
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.salt
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.img
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.realname
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.num
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.mobile
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.email
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.sex
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.dept_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.post
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.parent_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.last_login_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.user_id
     *
     * @return the value of crm_user.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.user_id
     *
     * @param userId the value for crm_user.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.username
     *
     * @return the value of crm_user.username
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.username
     *
     * @param username the value for crm_user.username
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.password
     *
     * @return the value of crm_user.password
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.password
     *
     * @param password the value for crm_user.password
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.salt
     *
     * @return the value of crm_user.salt
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.salt
     *
     * @param salt the value for crm_user.salt
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.img
     *
     * @return the value of crm_user.img
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.img
     *
     * @param img the value for crm_user.img
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.create_time
     *
     * @return the value of crm_user.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.create_time
     *
     * @param createTime the value for crm_user.create_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.realname
     *
     * @return the value of crm_user.realname
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.realname
     *
     * @param realname the value for crm_user.realname
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.num
     *
     * @return the value of crm_user.num
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.num
     *
     * @param num the value for crm_user.num
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.mobile
     *
     * @return the value of crm_user.mobile
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.mobile
     *
     * @param mobile the value for crm_user.mobile
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.email
     *
     * @return the value of crm_user.email
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.email
     *
     * @param email the value for crm_user.email
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.sex
     *
     * @return the value of crm_user.sex
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.sex
     *
     * @param sex the value for crm_user.sex
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.dept_id
     *
     * @return the value of crm_user.dept_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.dept_id
     *
     * @param deptId the value for crm_user.dept_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.post
     *
     * @return the value of crm_user.post
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.post
     *
     * @param post the value for crm_user.post
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.status
     *
     * @return the value of crm_user.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.status
     *
     * @param status the value for crm_user.status
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.parent_id
     *
     * @return the value of crm_user.parent_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.parent_id
     *
     * @param parentId the value for crm_user.parent_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.last_login_time
     *
     * @return the value of crm_user.last_login_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.last_login_time
     *
     * @param lastLoginTime the value for crm_user.last_login_time
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}