package zkz.bangong.pojo;

public class crmUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user_role.id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user_role.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user_role.role_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user_role.id
     *
     * @return the value of crm_user_role.id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user_role.id
     *
     * @param id the value for crm_user_role.id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user_role.user_id
     *
     * @return the value of crm_user_role.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user_role.user_id
     *
     * @param userId the value for crm_user_role.user_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user_role.role_id
     *
     * @return the value of crm_user_role.role_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user_role.role_id
     *
     * @param roleId the value for crm_user_role.role_id
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}