package zkz.bangong.pojo;

import java.util.Date;

public class jiaBanExamine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_jiaban_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    private Integer examineUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.examine_id
     *
     * @return the value of crm_jiaban_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.examine_id
     *
     * @param examineId the value for crm_jiaban_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.creater
     *
     * @return the value of crm_jiaban_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.creater
     *
     * @param creater the value for crm_jiaban_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.examine_type
     *
     * @return the value of crm_jiaban_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineType() {
        return examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.examine_type
     *
     * @param examineType the value for crm_jiaban_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineType(Integer examineType) {
        this.examineType = examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.context
     *
     * @return the value of crm_jiaban_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.context
     *
     * @param context the value for crm_jiaban_examine.context
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.remarks
     *
     * @return the value of crm_jiaban_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.remarks
     *
     * @param remarks the value for crm_jiaban_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.img_addr
     *
     * @return the value of crm_jiaban_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.img_addr
     *
     * @param imgAddr the value for crm_jiaban_examine.img_addr
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.batch_id
     *
     * @return the value of crm_jiaban_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.batch_id
     *
     * @param batchId the value for crm_jiaban_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.create_time
     *
     * @return the value of crm_jiaban_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.create_time
     *
     * @param createTime the value for crm_jiaban_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.update_time
     *
     * @return the value of crm_jiaban_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.update_time
     *
     * @param updateTime the value for crm_jiaban_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_jiaban_examine.examine_user_id
     *
     * @return the value of crm_jiaban_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public Integer getExamineUserId() {
        return examineUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_jiaban_examine.examine_user_id
     *
     * @param examineUserId the value for crm_jiaban_examine.examine_user_id
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    public void setExamineUserId(Integer examineUserId) {
        this.examineUserId = examineUserId;
    }
}