package zkz.bangong.pojo;

import java.util.Date;

public class qingJiaExamine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.qingjia_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer qingjiaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.context
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.spend_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer spendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.examiner_user_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer examinerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.imgs_addr
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private String imgsAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_qingjia_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    private Integer examineType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.examine_id
     *
     * @return the value of crm_qingjia_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.examine_id
     *
     * @param examineId the value for crm_qingjia_examine.examine_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.qingjia_type
     *
     * @return the value of crm_qingjia_examine.qingjia_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getQingjiaType() {
        return qingjiaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.qingjia_type
     *
     * @param qingjiaType the value for crm_qingjia_examine.qingjia_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setQingjiaType(Integer qingjiaType) {
        this.qingjiaType = qingjiaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.context
     *
     * @return the value of crm_qingjia_examine.context
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.context
     *
     * @param context the value for crm_qingjia_examine.context
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.start_time
     *
     * @return the value of crm_qingjia_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.start_time
     *
     * @param startTime the value for crm_qingjia_examine.start_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.end_time
     *
     * @return the value of crm_qingjia_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.end_time
     *
     * @param endTime the value for crm_qingjia_examine.end_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.spend_time
     *
     * @return the value of crm_qingjia_examine.spend_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.spend_time
     *
     * @param spendTime the value for crm_qingjia_examine.spend_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setSpendTime(Integer spendTime) {
        this.spendTime = spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.creater
     *
     * @return the value of crm_qingjia_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.creater
     *
     * @param creater the value for crm_qingjia_examine.creater
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.examiner_user_id
     *
     * @return the value of crm_qingjia_examine.examiner_user_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getExaminerUserId() {
        return examinerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.examiner_user_id
     *
     * @param examinerUserId the value for crm_qingjia_examine.examiner_user_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setExaminerUserId(Integer examinerUserId) {
        this.examinerUserId = examinerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.create_time
     *
     * @return the value of crm_qingjia_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.create_time
     *
     * @param createTime the value for crm_qingjia_examine.create_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.update_time
     *
     * @return the value of crm_qingjia_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.update_time
     *
     * @param updateTime the value for crm_qingjia_examine.update_time
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.remarks
     *
     * @return the value of crm_qingjia_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.remarks
     *
     * @param remarks the value for crm_qingjia_examine.remarks
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.imgs_addr
     *
     * @return the value of crm_qingjia_examine.imgs_addr
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public String getImgsAddr() {
        return imgsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.imgs_addr
     *
     * @param imgsAddr the value for crm_qingjia_examine.imgs_addr
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setImgsAddr(String imgsAddr) {
        this.imgsAddr = imgsAddr == null ? null : imgsAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.batch_id
     *
     * @return the value of crm_qingjia_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.batch_id
     *
     * @param batchId the value for crm_qingjia_examine.batch_id
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_qingjia_examine.examine_type
     *
     * @return the value of crm_qingjia_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public Integer getExamineType() {
        return examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_qingjia_examine.examine_type
     *
     * @param examineType the value for crm_qingjia_examine.examine_type
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    public void setExamineType(Integer examineType) {
        this.examineType = examineType;
    }
}