package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.chaiLvExamine;
import zkz.bangong.pojo.chaiLvExamineExample;

public interface chaiLvExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    long countByExample(chaiLvExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int deleteByExample(chaiLvExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int deleteByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int insert(chaiLvExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int insertSelective(chaiLvExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    List<chaiLvExamine> selectByExample(chaiLvExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    chaiLvExamine selectByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") chaiLvExamine record, @Param("example") chaiLvExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByExample(@Param("record") chaiLvExamine record, @Param("example") chaiLvExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByPrimaryKeySelective(chaiLvExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_chailv_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByPrimaryKey(chaiLvExamine record);
}