package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import zkz.bangong.pojo.crmAnnoun;
import zkz.bangong.pojo.crmAnnounExample;

public interface crmAnnounMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    long countByExample(crmAnnounExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int deleteByExample(crmAnnounExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int deleteByPrimaryKey(Integer announcementIdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int insert(crmAnnoun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int insertSelective(crmAnnoun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    List<crmAnnoun> selectByExample(crmAnnounExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    crmAnnoun selectByPrimaryKey(Integer announcementIdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") crmAnnoun record, @Param("example") crmAnnounExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int updateByExample(@Param("record") crmAnnoun record, @Param("example") crmAnnounExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int updateByPrimaryKeySelective(crmAnnoun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_oa_announcement
     *
     * @mbg.generated Tue Oct 22 23:11:18 CST 2019
     */
    int updateByPrimaryKey(crmAnnoun record);
/*查看用户可以查看的公告*/
    @Select("SELECT * FROM crm_oa_announcement  as a \n" +
            "            LEFT JOIN crm_user \n" +
            "            ON a.dept_id=crm_user.user_dept_id \n" +
            "\t\t\t\t\t\twhere (SELECT UNIX_TIMESTAMP()-UNIX_TIMESTAMP(a.start_time)>0\n" +
            "\t\t\t\t\t\tand  UNIX_TIMESTAMP(a.end_time)-UNIX_TIMESTAMP()>0\n" +
            "\t\t\t\t\t\t)\n" +
            "\t\t\t\t\t\tand crm_user.user_id=#{crnUserId}\n" +
            "            ORDER BY a.announcement_id_id DESC \n" +
            "\t\t\t\t\t\t ")
    List<crmAnnoun> selectMyAnnoun(Integer crmUserId);
@Select("SELECT * FROM crm_oa_announcement  as a \n" +
        "            LEFT JOIN crm_user \n" +
        "            ON a.dept_id=crm_user.user_dept_id \n" +
        "\t\t\t\t\t\twhere (SELECT UNIX_TIMESTAMP(a.end_time)-UNIX_TIMESTAMP()<0\n" +
        "\t\t\t\t\t\t)\n" +
        "\t\t\t\t\t\tand crm_user.user_id=#{crmUserId}\n" +
        "            ORDER BY a.announcement_id_id DESC ")
    List<crmAnnoun> selectMyEndAnnoun(Integer crmUserId);
}