package zkz.bangong.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import zkz.bangong.pojo.crmTask;
import zkz.bangong.pojo.crmTaskExample;
import zkz.bangong.pojo.crmUser;

public interface crmTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    long countByExample(crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByExample(crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insert(crmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insertSelective(crmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    List<crmTask> selectByExampleWithBLOBs(crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    List<crmTask> selectByExample(crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    crmTask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") crmTask record, @Param("example") crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") crmTask record, @Param("example") crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExample(@Param("record") crmTask record, @Param("example") crmTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKeySelective(crmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(crmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_task
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKey(crmTask record);

    /*查找全部人物类型的任务列表*/
    @Select("select * from crm_task where create_user_id=#{crmUserId} and status in(1,2,3)")
    List<crmTask> selectByStatusAll(@Param("crmUserId") Integer crmUserId);
    /*根据任务的优先级列表查找符合条件的所有人物类列表*/
    @Select("select * from crm_task where create_user_id=#{crmUserId} and priority in(0,1,2,3)")
    List<crmTask> selectByLevelAll(Integer crmUserId);
    @Select("seelct * from crm_task where create_user_id=#{crmUserId} and  ")
    List<crmTask> selectAllTime(int crmUserId, int num);

    /*根据员工姓名查找ID*/
    @Select("select user_id from crm_user where username=#{value}")
    Integer selectIdByName(String value);
    @Select("select * from crm_task where create_user_id=#{crmUserId}")
    List<crmTask> selectAll(Integer crmUserId);

    List<Map<Object,Object>> selectMonAndDay(Integer crmUserId);
    /*根据员工Id在员工表中查找到它的上级的Id*/
    @Select("select parent_id from crm_user where user_id=#{createUserId}")
    int selectParentIdByUserId(Integer createUserId);
/*根据员工的姓名查找员工的Id*/
    @Select("select username from crm_user where user_id=#{UserId}")
    String selectCrmNameById(Integer UserId);
/*根据员工的直属上级Id查找员工的直属下级的Id*/
    @Select("select user_id from crm_user where parent_id=#{crmUserId}")
    int selectLowerIdByPid(Integer crmUserId);
}