package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.crmUserRole;
import zkz.bangong.pojo.crmUserRoleExample;

public interface crmUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    long countByExample(crmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByExample(crmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insert(crmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insertSelective(crmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    List<crmUserRole> selectByExample(crmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    crmUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") crmUserRole record, @Param("example") crmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExample(@Param("record") crmUserRole record, @Param("example") crmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKeySelective(crmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user_role
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKey(crmUserRole record);
}