package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.crmUser;
import zkz.bangong.pojo.crmUserExample;

public interface crmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    long countByExample(crmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByExample(crmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insert(crmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int insertSelective(crmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    List<crmUser> selectByExample(crmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    crmUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") crmUser record, @Param("example") crmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByExample(@Param("record") crmUser record, @Param("example") crmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKeySelective(crmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated Tue Oct 22 12:39:04 CST 2019
     */
    int updateByPrimaryKey(crmUser record);
}