package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.examineCategory;
import zkz.bangong.pojo.examineCategoryExample;

public interface examineCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    long countByExample(examineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int deleteByExample(examineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insert(examineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insertSelective(examineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    List<examineCategory> selectByExample(examineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    examineCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") examineCategory record, @Param("example") examineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExample(@Param("record") examineCategory record, @Param("example") examineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByPrimaryKeySelective(examineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_category
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByPrimaryKey(examineCategory record);
}