package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.examineRecord;
import zkz.bangong.pojo.examineRecordExample;

public interface examineRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    long countByExample(examineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int deleteByExample(examineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insert(examineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insertSelective(examineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    List<examineRecord> selectByExample(examineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    examineRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") examineRecord record, @Param("example") examineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExample(@Param("record") examineRecord record, @Param("example") examineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByPrimaryKeySelective(examineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_record
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByPrimaryKey(examineRecord record);
}