package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.examineLog;
import zkz.bangong.pojo.examineLogExample;

public interface examineLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    long countByExample(examineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int deleteByExample(examineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insert(examineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int insertSelective(examineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    List<examineLog> selectByExample(examineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") examineLog record, @Param("example") examineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_examine_log
     *
     * @mbg.generated Wed Oct 23 09:15:55 CST 2019
     */
    int updateByExample(@Param("record") examineLog record, @Param("example") examineLogExample example);
}