package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.jiaBanExamine;
import zkz.bangong.pojo.jiaBanExamineExample;

public interface jiaBanExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    long countByExample(jiaBanExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int deleteByExample(jiaBanExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int deleteByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int insert(jiaBanExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int insertSelective(jiaBanExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    List<jiaBanExamine> selectByExample(jiaBanExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    jiaBanExamine selectByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") jiaBanExamine record, @Param("example") jiaBanExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByExample(@Param("record") jiaBanExamine record, @Param("example") jiaBanExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByPrimaryKeySelective(jiaBanExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_jiaban_examine
     *
     * @mbg.generated Wed Oct 23 12:33:04 CST 2019
     */
    int updateByPrimaryKey(jiaBanExamine record);
}