package zkz.bangong.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zkz.bangong.pojo.qingJiaExamine;
import zkz.bangong.pojo.qingJiaExamineExample;

public interface qingJiaExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    long countByExample(qingJiaExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int deleteByExample(qingJiaExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int deleteByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int insert(qingJiaExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int insertSelective(qingJiaExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    List<qingJiaExamine> selectByExample(qingJiaExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    qingJiaExamine selectByPrimaryKey(Integer examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") qingJiaExamine record, @Param("example") qingJiaExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int updateByExample(@Param("record") qingJiaExamine record, @Param("example") qingJiaExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int updateByPrimaryKeySelective(qingJiaExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_qingjia_examine
     *
     * @mbg.generated Wed Oct 23 12:34:30 CST 2019
     */
    int updateByPrimaryKey(qingJiaExamine record);
}